name: EPG Update

on:
  watch:
    types: [started]
  schedule:
    - cron: '15 16,18,20,22,0,2,4,6,8,10,12,14 * * *'
  workflow_dispatch:
    inputs:
      #logLevel:
        #description: 'Log level'
        #required: true
        #default: 'warning'
      tags:
        description: 'Manual trigger'
        required: true
        default: 'Manual Test'

permissions:
  contents: write
  
env:
  TZ: Asia/Shanghai

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: GetTime
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S CST')"
      
    - name: Update
      run: |
        wget https://epg.112114.xyz/pp.xml -O 112114.xml
        mv 112114.xml epg
        
    - name: Push
      run: |
        git config --local user.name "huangsuming"
        git config --local user.email "huangsuming@users.noreply.github.com"
        git add epg/112114.xml
        git commit -m "${{ steps.date.outputs.date }}"
        git push origin main
