name: EPG Update
  
env:
  TZ: Asia/Shanghai
  
on:
  watch:
    types: [started]
  schedule:
    - cron: '15 0,2,4,6,8,10,12,14,16,18,20,22 * * *'
  workflow_dispatch:
    inputs:
      #logLevel:
        #description: 'Log level'
        #required: true
        #default: 'warning'
      tags:
        description: 'Manual trigger'
        required: true
        default: 'Manual Test'

permissions:
  contents: write

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: GetTime
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S CST')"
      
    - name: Update
      run: |
        wget https://epg.112114.xyz/pp.xml -O 112114.xml
        wget https://raw.githubusercontent.com/fanmingming/live/master/tv/m3u/ipv6.m3u -O fmm.m3u
        wget https://raw.githubusercontent.com/tansuotv/IPTVindex/master/tv.txt -O tst.txt
        mv 112114.xml epg
        mv fmm.m3u tst.txt list
        
    - name: Push
      run: |
        git config --local user.name "huangsuming"
        git config --local user.email "huangsuming@users.noreply.github.com"
        git add epg/112114.xml list/fmm.m3u list/tst.txt
        git commit -m "${{ steps.date.outputs.date }}"
        git pull
        git push origin main
