name: HOST Update
  
env:
  TZ: Asia/Shanghai
  
on:
  watch:
    types: [started]
  schedule:
    #默认为国际标准时间(UTC),比北京慢8小时.
    - cron: 15 13 * * *
  workflow_dispatch:
    inputs:
      #logLevel:
        #description: 'Log level'
        #required: true
        #default: 'warning'
      tags:
        description: 'Manual trigger'
        required: true
        default: 'Manual Test'

permissions:
  contents: write

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: GetTime
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S CST')"
      
    - name: Update
      run: |
        wget https://hosts.gitcdn.top/hosts.txt -O gitcdn
        wget https://raw.hellogithub.com/hosts -O hello
        mv gitcdn hello host

https://raw.hellogithub.com/hosts
        
    - name: Push
      run: |
        git config --local user.name "huangsuming"
        git config --local user.email "huangsuming@users.noreply.github.com"
        git add host/gitcdn host/hello
        git commit -m "${{ steps.date.outputs.date }}"
        git push origin main
        
        
