name: Live Update
  
env:
  TZ: Asia/Shanghai
  
on:
  watch:
    types: [started]
  schedule:
    - cron: 15 22 * * *
  workflow_dispatch:
    inputs:
      #logLevel:
        #description: 'Log level'
        #required: true
        #default: 'warning'
      tags:
        description: 'Manual trigger'
        required: true
        default: 'Manual Test'

permissions:
  contents: write

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: GetTime
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S CST')"
      
    - name: Update
      run: |
        wget https://raw.githubusercontent.com/fanmingming/live/master/tv/m3u/ipv6.m3u -O fmm.m3u8
        wget https://raw.githubusercontent.com/suxuang/myIPTV/master/ipv6.m3u -O sux.m3u8
        wget https://raw.githubusercontent.com/tansuotv/IPTVindex/master/tv.txt -O tst.txt
        echo 'Clone from fmm' >iptv.txt
        cat fmm.m3u8|sed '/^\s*$/d' >> iptv.txt
        echo -e >> iptv.txt
        echo -e >> iptv.txt
        echo 'Clone from sux' >>iptv.txt
        cat sux.m3u8|sed '/^\s*$/d' >> iptv.txt
        echo -e >> iptv.txt
        echo -e >> iptv.txt
        echo 'Clone from tst' >>iptv.txt
        cat tst.txt|sed '/^\s*$/d' >> iptv.txt
        echo -e >> iptv.txt
        echo -e >> iptv.txt
        rm -f fmm.m3u8 sux.m3u8 tst.txt
        mv iptv.txt list
        
    - name: Push
      run: |
        git config --local user.name "huangsuming"
        git config --local user.email "huangsuming@users.noreply.github.com"
        git add list/iptv.txt
        git commit -m "${{ steps.date.outputs.date }}"
        git push  origin main
        
